#!/bin/bash

echo -e "This script assumes that the PC is completely setup with a vector_ws.\n\n"

read -r -p "Are you absolutely sure you want to continue? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    echo "Starting setup......"
    sleep 1
else
    exit 1
fi

sudo apt-get install python-pip blueman
sudo pip install evdev
sudo pip install pyudev

sudo cp /home/$USER/vector_ws/src/vector_common/vector_third_party/ds4drv/udev/50-ds4drv.rules /etc/udev/rules.d/
sudo cp /home/$USER/vector_ws/src/vector_common/vector_third_party/ds4drv/ds4drv.conf /etc/
sudo udevadm control --reload-rules
sudo udevadm trigger
